name: cicd

on:
  push:
    branches:
      - v3.0.0-openmldb
    tags:
      - v*
  pull_request:
  workflow_dispatch:

jobs:
  build_spark_distribution:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/4paradigm/hybridsql:0.4.1

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: compile
        run: |
          ./dev/make-distribution.sh --name openmldbspark --tgz -Phadoop-2.7 -Pyarn -Pallinone

      - name: Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            spark-*-bin-openmldbspark.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
